# Generated by Django 4.1.7 on 2023-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='post.tag'),
        ),
    ]
