# Generated by Django 4.1.7 on 2023-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_media_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
