# Generated by Django 4.1.7 on 2023-06-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
