# Generated by Django 4.1.7 on 2023-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storystream',
            name='story',
            field=models.ManyToManyField(related_name='stories', to='stories.story'),
        ),
    ]
