# Generated by Django 4.1.7 on 2023-05-17 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_alter_storystream_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storystream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_user_stream', to=settings.AUTH_USER_MODEL),
        ),
    ]
