# Generated by Django 4.1.7 on 2023-05-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_user_alter_storystream_story_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='content',
            new_name='images',
        ),
    ]
