# Generated by Django 4.1.7 on 2023-06-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text_preview',
        ),
    ]
