# Generated by Django 4.1.7 on 2023-03-23 21:25

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_profile_bio_alter_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='assets1/default-user.png', null=True, upload_to=userauth.models.user_directory_path, verbose_name='image'),
        ),
    ]
