# Generated by Django 4.1.7 on 2023-03-23 21:35

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauth.models.user_directory_path, verbose_name='image'),
        ),
    ]
