# Generated by Django 4.1.7 on 2023-04-17 14:12

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_tag'),
        ('userauth', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to=userauth.models.user_directory_path, verbose_name='image'),
        ),
    ]
